version: '2'
services:
    blog-app:
        image: blog
        external_links:
            - blog-postgresql:postgresql
            - blog-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/blog
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    blog-postgresql:
        extends:
            file: postgresql.yml
            service: blog-postgresql
    blog-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: blog-elasticsearch
